version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - inlira-db:/var/lib/postgresql/data

  inlira:
    build:
      context: .
    environment:
      DB_SCHEMA: db_df_inlira
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    ports:
      - '4000:4000'
        
volumes:
  inlira-db: